controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

saveScoreGame:
    path: /saveScore
    controller: App\Controller\GamesController::saveScore